#the program to run
program: centralized.py

#method 
method : random

#metric to optimize
metric:
    name: miou
    goal: maximize
  
#parameters space to search
parameters:
  lr:
    distribution: log_uniform
    min: 1e-4
    max: 1e-2
  
  batch_size:
    values: [8, 16, 32, 64, 128]

  optmizer: ['adam', 'sgd']