method : grid

metric:
  name: loss
  goal: minimize

parameters:

  rndRot:
    parameters:
      active:
        value: False
      maxDeg:
        value: 10
  
  rndHzFlip:
    value: False

  rndVertFlip:
    value: False

  colorJitter:
    parameters:
      active:
        value: True

      brightness:
        value: 0

      contrast:
        value: 0
      
      saturation:
        value: 0
      
      hue:
        values: [0.05, 0.15]
