method : grid

metric:
  name: loss
  goal: minimize

parameters:

  rndRot:
    parameters:
      active:
        values: [True, False]
      maxDeg:
        value: 10
  
  rndHzFlip:
    values: [True, False]

  rndVertFlip:
    value: [True, False]

  colorJitter:
    parameters:
      active:
        values: [True, False]

      brightness:
        value: 

      contrast:
        value: 
      
      saturation:
        value: 
      
      hue:
        value: 
