# SGD lr = 0.1, momentum = 0.9, weight_decay: 0.0001, scheduler = pol
optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9
scheduler:
  name: PolynomialLR
  power: 0.9
  total_iters: 50