method : grid

metric:
  name: loss
  goal: minimize

parameters:
  optimizer:
    parameters:

      name: 
        value: Adam
  
      lr:
        value: 0.1
  
  scheduler:
    parameters:
      name:
        value: StepLR
  
      gamma: #ExpLr, StepLr
        values: [0.01, 0.1, 0.33]

      step_size: #StepLR
        values: [2, 4]